// Variables - const
let customer = "juan";
let priceDiscount = 220;

// - const cannot be reassigned 
// - const no puede ser reasignado
// customer = 20
// cannot be declared without an initial value
// no puede ser declarado sin un valor inicial
// const price

console.log(price);
console.log(customer);
console.log(priceDiscount);

// with const, you cannot modify the values, unlike let
// con const, no puedes modificar los valores, a diferencia de let
